import type {
	JsonSchemaObject,
	OpenApiDocument,
	OpenApiOperation,
	OpenApiParameter,
} from '../openapi/mod.ts';
import { isRecord, toIdentifier, toPascalIdentifier } from './helpers.ts';

interface RouteModel {
	readonly namespace: string;
	readonly methodName: string;
	readonly method: string;
	readonly path: string;
	readonly permission: string;
	readonly operation: OpenApiOperation;
	readonly typePrefix: string;
	readonly fixedHeaders: readonly FixedHeader[];
}

interface FixedHeader {
	readonly name: string;
	readonly value: string;
}

export function collectRoutes(document: OpenApiDocument): RouteModel[] {
	const routes: RouteModel[] = [];
	for (const [path, methods] of Object.entries(document.paths)) {
		for (const [rawMethod, operation] of Object.entries(methods)) {
			const permission = resolvePermission(operation, rawMethod, path);
			const namespace = resolveNamespace(operation, permission);
			const methodName = toIdentifier(
				resolveMethodName(permission, namespace),
			);
			routes.push({
				namespace,
				methodName,
				method: rawMethod.toUpperCase(),
				path: resolveClientPath(operation, path),
				permission,
				operation,
				typePrefix: toPascalIdentifier(`${namespace}.${methodName}`),
				fixedHeaders: collectFixedHeaders(operation),
			});
		}
	}
	return dedupeRouteMethodNames(routes).sort((left, right) =>
		`${left.namespace}.${left.methodName}`.localeCompare(
			`${right.namespace}.${right.methodName}`,
		)
	);
}

function resolvePermission(
	operation: OpenApiOperation,
	method: string,
	path: string,
): string {
	const routeName = operation['x-codexa-route-name'];
	if (typeof routeName === 'string' && routeName.trim() !== '') {
		return routeName;
	}
	if (
		typeof operation.operationId === 'string' &&
		operation.operationId !== ''
	) {
		return operation.operationId;
	}
	return `${method.toLowerCase()}${path.replace(/[^a-zA-Z0-9]+/g, '.')}`;
}

function resolveNamespace(
	operation: OpenApiOperation,
	permission: string,
): string {
	const pluginName = operation['x-codexa-plugin'];
	if (typeof pluginName === 'string' && pluginName.trim() !== '') {
		return toIdentifier(pluginName);
	}
	const firstTag = operation.tags?.find((tag) => tag.trim() !== '');
	if (firstTag !== undefined) return toIdentifier(firstTag);
	return toIdentifier(permission.split('.')[0] ?? 'api');
}

function resolveClientPath(
	operation: OpenApiOperation,
	openApiPath: string,
): string {
	const originalPath = operation['x-codexa-original-path'];
	if (typeof originalPath === 'string' && originalPath.trim() !== '') {
		return originalPath;
	}
	return openApiPath.replace(/\{([^}]+)\}/g, ':$1');
}

function resolveMethodName(permission: string, namespace: string): string {
	const parts = permission.split('.').filter(Boolean);
	if (parts[0] === namespace && parts.length > 1) {
		return parts.slice(1).join('.');
	}
	return parts.length > 1 ? parts.slice(1).join('.') : permission;
}

function collectFixedHeaders(operation: OpenApiOperation): FixedHeader[] {
	const version = operation['x-codexa-version'];
	if (version === undefined) return [];
	return [{
		name: operation['x-codexa-version-header'] ?? 'X-Version',
		value: version,
	}];
}

function dedupeRouteMethodNames(routes: readonly RouteModel[]): RouteModel[] {
	const groups = new Map<string, RouteModel[]>();
	for (const route of routes) {
		const key = `${route.namespace}.${route.methodName}`;
		const group = groups.get(key) ?? [];
		group.push(route);
		groups.set(key, group);
	}

	const used = new Set<string>();
	return routes.map((route) => {
		const key = `${route.namespace}.${route.methodName}`;
		const group = groups.get(key) ?? [];
		if (group.length === 1 && !used.has(key)) {
			used.add(key);
			return route;
		}

		const methodName = uniqueMethodName(route, used);
		used.add(`${route.namespace}.${methodName}`);
		return {
			...route,
			methodName,
			typePrefix: toPascalIdentifier(`${route.namespace}.${methodName}`),
		};
	});
}

function uniqueMethodName(route: RouteModel, used: Set<string>): string {
	const candidates = [
		route.operation['x-codexa-version'] === undefined
			? undefined
			: `${route.methodName}.v.${route.operation['x-codexa-version']}`,
		route.operation.operationId,
		`${route.methodName}.${route.method}.${route.path}`,
	];
	for (const candidate of candidates) {
		if (candidate === undefined || candidate === '') continue;
		const methodName = toIdentifier(candidate);
		if (!used.has(`${route.namespace}.${methodName}`)) return methodName;
	}

	let index = 2;
	while (used.has(`${route.namespace}.${route.methodName}${index}`)) index++;
	return `${route.methodName}${index}`;
}

export function renderReadme(packageName: string, clientName: string): string {
	return `# ${packageName}

Generated by \`@codexa/core/sdk\`.

\`\`\`ts
import { ${clientName} } from '${packageName}';

const api = ${clientName}.create({ baseUrl: 'http://localhost:8000' });
await api.auth.session();
\`\`\`
`;
}

export function renderRuntimeSource(input: {
	readonly clientName: string;
	readonly defaultBaseUrl?: string;
	readonly routes: readonly RouteModel[];
}): string {
	const namespaces = groupRoutes(input.routes);
	return `/* This file was generated by @codexa/core/sdk. Do not edit by hand. */

function mergeHeaders(...items) {
\tconst headers = new Headers();
\tfor (const item of items) {
\t\tif (item === undefined) continue;
\t\tnew Headers(item).forEach((value, key) => headers.set(key, value));
\t}
\treturn headers;
}

function mergeRouteInput(input, fixedHeaders) {
\tif (fixedHeaders.length === 0) return input;
\treturn {
\t\t...input,
\t\theaders: mergeHeaders(input.headers, Object.fromEntries(fixedHeaders)),
\t};
}

function encodePath(path, params) {
\tconst next = path.replace(
\t\t/:([a-zA-Z_][a-zA-Z0-9_]*)\\??/g,
\t\t(_, key) => {
\t\t\tconst value = params?.[key];
\t\t\treturn value === undefined || value === null
\t\t\t\t? ''
\t\t\t\t: encodeURIComponent(String(value));
\t\t},
\t);
\treturn next.replace(/\\/+/g, '/').replace(/\\/$/, '') || '/';
}

function appendQuery(path, query) {
\tif (query === undefined) return path;
\tconst search = new URLSearchParams();
\tfor (const [key, value] of Object.entries(query)) {
\t\tif (value === undefined || value === null) continue;
\t\tif (Array.isArray(value)) {
\t\t\tfor (const item of value) search.append(key, String(item));
\t\t\tcontinue;
\t\t}
\t\tsearch.set(key, String(value));
\t}
\tconst serialized = search.toString();
\treturn serialized ? \`\${path}?\${serialized}\` : path;
}

function resolveUrl(baseUrl, path) {
\tif (baseUrl === '') return path;
\treturn new URL(path, baseUrl).toString();
}

function responseData(payload) {
\tif (payload && typeof payload === 'object' && 'data' in payload) {
\t\treturn payload.data;
\t}
\treturn payload;
}

function createExecutors(raw) {
\tconst res = raw.then(async (response) => {
\t\tif (response.status === 204) return undefined;
\t\treturn await response.json();
\t});
\tconst data = res.then(responseData);
\treturn {
\t\traw,
\t\tres,
\t\tdata,
\t\tthen: data.then.bind(data),
\t\tcatch: data.catch.bind(data),
\t\tfinally: data.finally.bind(data),
\t};
}

export class ${input.clientName} {
\tstatic options = {};

${renderRuntimeInstanceFields(namespaces)}

\tconstructor(options = {}) {
\t\tthis.options = options;
${renderRuntimeInstanceNamespaceAssignments(namespaces)}
\t}

\tstatic create(options = {}) {
\t\treturn new this(options);
\t}

\tstatic init(options = {}) {
\t\tthis.options = options;
\t}

\tstatic setPermissions(permissions) {
\t\tthis.options = { ...this.options, permissions };
\t}

\tstatic isPermitted(permissionOrMethod) {
\t\treturn isPermitted(this.options, permissionOrMethod);
\t}

\tstatic checkPermission(permissionOrMethod) {
\t\tcheckPermission(this.options, permissionOrMethod);
\t}

\tstatic request(method, path, input = {}) {
\t\treturn request(this.options, method, path, input);
\t}

\tsetPermissions(permissions) {
\t\tthis.options = { ...this.options, permissions };
\t}

\tisPermitted(permissionOrMethod) {
\t\treturn isPermitted(this.options, permissionOrMethod);
\t}

\tcheckPermission(permissionOrMethod) {
\t\tcheckPermission(this.options, permissionOrMethod);
\t}

\trequest(method, path, input = {}) {
\t\treturn request(this.options, method, path, input);
\t}

${
		Array.from(namespaces.entries()).map(([namespace, routes]) =>
			renderRuntimeStaticNamespace(input.clientName, namespace, routes)
		).join('\n\n')
	}
}

function isPermitted(options, permissionOrMethod) {
\tconst permission = typeof permissionOrMethod === 'string'
\t\t? permissionOrMethod
\t\t: permissionOrMethod.__permission;
\tif (permission === undefined) return false;
\tconst permissions = options.permissions;
\treturn permissions === undefined || permissions.includes('*') ||
\t\tpermissions.includes(permission);
}

function checkPermission(options, permissionOrMethod) {
\tif (!isPermitted(options, permissionOrMethod)) {
\t\tconst permission = typeof permissionOrMethod === 'string'
\t\t\t? permissionOrMethod
\t\t\t: permissionOrMethod.__permission;
\t\tthrow new Error(\`Missing permission: \${permission ?? 'unknown'}\`);
\t}
}

function request(options, method, path, input = {}) {
\tconst raw = (async () => {
\t\tconst fetcher = options.fetch ?? fetch;
\t\tconst configuredHeaders = typeof options.headers === 'function'
\t\t\t? await options.headers()
\t\t\t: options.headers;
\t\tconst headers = mergeHeaders(configuredHeaders, input.headers);
\t\tlet body;
\t\tif (input.body !== undefined) {
\t\t\tif (!headers.has('content-type')) {
\t\t\t\theaders.set('content-type', 'application/json');
\t\t\t}
\t\t\tbody = headers.get('content-type')?.includes('application/json')
\t\t\t\t? JSON.stringify(input.body)
\t\t\t\t: input.body;
\t\t}
\t\tconst url = resolveUrl(
\t\t\toptions.baseUrl ?? ${JSON.stringify(input.defaultBaseUrl ?? '')},
\t\t\tappendQuery(encodePath(path, input.params), input.query),
\t\t);
\t\tconst response = await fetcher(url, {
\t\t\tmethod,
\t\t\theaders,
\t\t\tbody,
\t\t\tsignal: input.signal,
\t\t});
\t\tif (!response.ok) {
\t\t\tthrow new Error(await response.text() || response.statusText);
\t\t}
\t\treturn response;
\t})();
\treturn createExecutors(raw);
}
`;
}

export function renderDeclarationSource(input: {
	readonly clientName: string;
	readonly routes: readonly RouteModel[];
}): string {
	const namespaces = groupRoutes(input.routes);
	return `/* This file was generated by @codexa/core/sdk. Do not edit by hand. */

${input.routes.map(renderRouteTypes).join('\n')}
export type CodexaSdkHeaders =
\t| HeadersInit
\t| (() => HeadersInit | Promise<HeadersInit>);

export interface CodexaSdkOptions {
\treadonly baseUrl?: string;
\treadonly headers?: CodexaSdkHeaders;
\treadonly fetch?: typeof fetch;
\treadonly permissions?: readonly string[];
}

export interface CodexaRequestOptions {
\treadonly params?: Record<string, string | number | boolean | null | undefined>;
\treadonly query?: Record<string, unknown>;
\treadonly body?: unknown;
\treadonly headers?: HeadersInit;
\treadonly signal?: AbortSignal;
}

export interface CodexaRequestExecutors<TResponse> {
\treadonly raw: Promise<Response>;
\treadonly res: Promise<TResponse>;
\treadonly data: Promise<TResponse extends { data: infer Data } ? Data : TResponse>;
\tthen: Promise<TResponse extends { data: infer Data } ? Data : TResponse>['then'];
\tcatch: Promise<TResponse extends { data: infer Data } ? Data : TResponse>['catch'];
\tfinally: Promise<TResponse extends { data: infer Data } ? Data : TResponse>['finally'];
}

export type CodexaSdkMethod<TInput, TResponse> =
\t& ((input?: TInput) => CodexaRequestExecutors<TResponse>)
\t& { readonly __permission: string };

export declare class ${input.clientName} {
\tstatic options: CodexaSdkOptions;
\tstatic create(options?: CodexaSdkOptions): ${input.clientName};
\tstatic init(options?: CodexaSdkOptions): void;
\tstatic setPermissions(permissions: readonly string[]): void;
\tstatic isPermitted(permissionOrMethod: string | { readonly __permission?: string }): boolean;
\tstatic checkPermission(permissionOrMethod: string | { readonly __permission?: string }): void;
\tstatic request<TResponse>(
\t\tmethod: string,
\t\tpath: string,
\t\tinput?: CodexaRequestOptions,
\t): CodexaRequestExecutors<TResponse>;

${
		Array.from(namespaces.entries()).map(([namespace, routes]) =>
			renderDeclarationNamespace(namespace, routes, { static: true })
		).join('\n\n')
	}

\toptions: CodexaSdkOptions;
\tconstructor(options?: CodexaSdkOptions);
\tsetPermissions(permissions: readonly string[]): void;
\tisPermitted(permissionOrMethod: string | { readonly __permission?: string }): boolean;
\tcheckPermission(permissionOrMethod: string | { readonly __permission?: string }): void;
\trequest<TResponse>(
\t\tmethod: string,
\t\tpath: string,
\t\tinput?: CodexaRequestOptions,
\t): CodexaRequestExecutors<TResponse>;

${
		Array.from(namespaces.entries()).map(([namespace, routes]) =>
			renderDeclarationNamespace(namespace, routes, { static: false })
		).join('\n\n')
	}
}
`;
}

export function renderClientSource(input: {
	readonly clientName: string;
	readonly defaultBaseUrl?: string;
	readonly routes: readonly RouteModel[];
}): string {
	const namespaces = groupRoutes(input.routes);
	return `/* This file was generated by @codexa/core/sdk. Do not edit by hand. */

${input.routes.map(renderRouteTypes).join('\n')}
export type CodexaSdkHeaders =
\t| HeadersInit
\t| (() => HeadersInit | Promise<HeadersInit>);

export interface CodexaSdkOptions {
\treadonly baseUrl?: string;
\treadonly headers?: CodexaSdkHeaders;
\treadonly fetch?: typeof fetch;
\treadonly permissions?: readonly string[];
}

export interface CodexaRequestOptions {
\treadonly params?: Record<string, string | number | boolean | null | undefined>;
\treadonly query?: Record<string, unknown>;
\treadonly body?: unknown;
\treadonly headers?: HeadersInit;
\treadonly signal?: AbortSignal;
}

export interface CodexaRequestExecutors<TResponse> {
\treadonly raw: Promise<Response>;
\treadonly res: Promise<TResponse>;
\treadonly data: Promise<TResponse extends { data: infer Data } ? Data : TResponse>;
\tthen: Promise<TResponse extends { data: infer Data } ? Data : TResponse>['then'];
\tcatch: Promise<TResponse extends { data: infer Data } ? Data : TResponse>['catch'];
\tfinally: Promise<TResponse extends { data: infer Data } ? Data : TResponse>['finally'];
}

export type CodexaSdkMethod<TInput, TResponse> =
\t& ((input?: TInput) => CodexaRequestExecutors<TResponse>)
\t& { readonly __permission: string };

function mergeHeaders(...items: readonly (HeadersInit | undefined)[]): Headers {
\tconst headers = new Headers();
\tfor (const item of items) {
\t\tif (item === undefined) continue;
\t\tnew Headers(item).forEach((value, key) => headers.set(key, value));
\t}
\treturn headers;
}

function mergeRouteInput(
\tinput: CodexaRequestOptions,
\tfixedHeaders: readonly (readonly [string, string])[],
): CodexaRequestOptions {
\tif (fixedHeaders.length === 0) return input;
\treturn {
\t\t...input,
\t\theaders: mergeHeaders(input.headers, Object.fromEntries(fixedHeaders)),
\t};
}

function encodePath(path: string, params?: CodexaRequestOptions['params']): string {
\tconst next = path.replace(
\t\t/:([a-zA-Z_][a-zA-Z0-9_]*)\\??/g,
\t\t(_, key: string) => {
\t\t\tconst value = params?.[key];
\t\t\treturn value === undefined || value === null
\t\t\t\t? ''
\t\t\t\t: encodeURIComponent(String(value));
\t\t},
\t);
\treturn next.replace(/\\/+/g, '/').replace(/\\/$/, '') || '/';
}

function appendQuery(path: string, query?: CodexaRequestOptions['query']): string {
\tif (query === undefined) return path;
\tconst search = new URLSearchParams();
\tfor (const [key, value] of Object.entries(query)) {
\t\tif (value === undefined || value === null) continue;
\t\tif (Array.isArray(value)) {
\t\t\tfor (const item of value) search.append(key, String(item));
\t\t\tcontinue;
\t\t}
\t\tsearch.set(key, String(value));
\t}
\tconst serialized = search.toString();
\treturn serialized ? \`\${path}?\${serialized}\` : path;
}

function resolveUrl(baseUrl: string, path: string): string {
\tif (baseUrl === '') return path;
\treturn new URL(path, baseUrl).toString();
}

function responseData<TResponse>(
\tpayload: TResponse,
): TResponse extends { data: infer Data } ? Data : TResponse {
\tif (payload && typeof payload === 'object' && 'data' in payload) {
\t\treturn (payload as { data: unknown }).data as TResponse extends {
\t\t\tdata: infer Data;
\t\t} ? Data
\t\t\t: TResponse;
\t}
\treturn payload as TResponse extends { data: infer Data } ? Data : TResponse;
}

function createExecutors<TResponse>(
\traw: Promise<Response>,
): CodexaRequestExecutors<TResponse> {
\tconst res = raw.then(async (response) => {
\t\tif (response.status === 204) return undefined as TResponse;
\t\treturn await response.json() as TResponse;
\t});
\tconst data = res.then(responseData<TResponse>);
\treturn {
\t\traw,
\t\tres,
\t\tdata,
\t\tthen: data.then.bind(data),
\t\tcatch: data.catch.bind(data),
\t\tfinally: data.finally.bind(data),
\t};
}

export class ${input.clientName} {
\tstatic options: CodexaSdkOptions = {};

${renderInstanceFields(namespaces)}

\tconstructor(options: CodexaSdkOptions = {}) {
\t\tthis.options = options;
${renderInstanceNamespaceAssignments(namespaces)}
\t}

\tstatic create(options: CodexaSdkOptions = {}): ${input.clientName} {
\t\treturn new this(options);
\t}

\tstatic init(options: CodexaSdkOptions = {}): void {
\t\tthis.options = options;
\t}

\tstatic setPermissions(permissions: readonly string[]): void {
\t\tthis.options = { ...this.options, permissions };
\t}

\tstatic isPermitted(
\t\tpermissionOrMethod: string | { readonly __permission?: string },
\t): boolean {
\t\treturn isPermitted(this.options, permissionOrMethod);
\t}

\tstatic checkPermission(
\t\tpermissionOrMethod: string | { readonly __permission?: string },
\t): void {
\t\tcheckPermission(this.options, permissionOrMethod);
\t}

\tstatic request<TResponse>(
\t\tmethod: string,
\t\tpath: string,
\t\tinput: CodexaRequestOptions = {},
\t): CodexaRequestExecutors<TResponse> {
\t\treturn request<TResponse>(this.options, method, path, input);
\t}

\tsetPermissions(permissions: readonly string[]): void {
\t\tthis.options = { ...this.options, permissions };
\t}

\tisPermitted(
\t\tpermissionOrMethod: string | { readonly __permission?: string },
\t): boolean {
\t\treturn isPermitted(this.options, permissionOrMethod);
\t}

\tcheckPermission(
\t\tpermissionOrMethod: string | { readonly __permission?: string },
\t): void {
\t\tcheckPermission(this.options, permissionOrMethod);
\t}

\trequest<TResponse>(
\t\tmethod: string,
\t\tpath: string,
\t\tinput: CodexaRequestOptions = {},
\t): CodexaRequestExecutors<TResponse> {
\t\treturn request<TResponse>(this.options, method, path, input);
\t}

${
		Array.from(namespaces.entries()).map(([namespace, routes]) =>
			renderStaticNamespace(input.clientName, namespace, routes)
		).join('\n\n')
	}
}

function isPermitted(
\toptions: CodexaSdkOptions,
\tpermissionOrMethod: string | { readonly __permission?: string },
): boolean {
\tconst permission = typeof permissionOrMethod === 'string'
\t\t? permissionOrMethod
\t\t: permissionOrMethod.__permission;
\tif (permission === undefined) return false;
\tconst permissions = options.permissions;
\treturn permissions === undefined || permissions.includes('*') ||
\t\tpermissions.includes(permission);
}

function checkPermission(
\toptions: CodexaSdkOptions,
\tpermissionOrMethod: string | { readonly __permission?: string },
): void {
\tif (!isPermitted(options, permissionOrMethod)) {
\t\tconst permission = typeof permissionOrMethod === 'string'
\t\t\t? permissionOrMethod
\t\t\t: permissionOrMethod.__permission;
\t\tthrow new Error(\`Missing permission: \${permission ?? 'unknown'}\`);
\t}
}

function request<TResponse>(
\toptions: CodexaSdkOptions,
\tmethod: string,
\tpath: string,
\tinput: CodexaRequestOptions = {},
): CodexaRequestExecutors<TResponse> {
\tconst raw = (async () => {
\t\tconst fetcher = options.fetch ?? fetch;
\t\tconst configuredHeaders = typeof options.headers === 'function'
\t\t\t? await options.headers()
\t\t\t: options.headers;
\t\tconst headers = mergeHeaders(configuredHeaders, input.headers);
\t\tlet body: BodyInit | undefined;
\t\tif (input.body !== undefined) {
\t\t\tif (!headers.has('content-type')) {
\t\t\t\theaders.set('content-type', 'application/json');
\t\t\t}
\t\t\tbody = headers.get('content-type')?.includes('application/json')
\t\t\t\t? JSON.stringify(input.body)
\t\t\t\t: input.body as BodyInit;
\t\t}
\t\tconst url = resolveUrl(
\t\t\toptions.baseUrl ?? ${JSON.stringify(input.defaultBaseUrl ?? '')},
\t\t\tappendQuery(encodePath(path, input.params), input.query),
\t\t);
\t\tconst response = await fetcher(url, {
\t\t\tmethod,
\t\t\theaders,
\t\t\tbody,
\t\t\tsignal: input.signal,
\t\t});
\t\tif (!response.ok) {
\t\t\tthrow new Error(await response.text() || response.statusText);
\t\t}
\t\treturn response;
\t})();
\treturn createExecutors<TResponse>(raw);
}
`;
}

function groupRoutes(
	routes: readonly RouteModel[],
): Map<string, readonly RouteModel[]> {
	const groups = new Map<string, RouteModel[]>();
	for (const route of routes) {
		const group = groups.get(route.namespace) ?? [];
		group.push(route);
		groups.set(route.namespace, group);
	}
	return new Map(
		Array.from(groups.entries()).map((
			[key, value],
		) => [key, Object.freeze(value)]),
	);
}

function renderRouteTypes(route: RouteModel): string {
	const parameters = route.operation.parameters ?? [];
	const params = parameters.filter((parameter) => parameter.in === 'path');
	const query = parameters.filter((parameter) => parameter.in === 'query');
	const body = firstRequestBodySchema(route.operation);
	const response = firstSuccessResponseSchema(route.operation);
	const inputType = `${route.typePrefix}Input`;
	return `export type ${route.typePrefix}Params = ${parametersToType(params)};
export type ${route.typePrefix}Query = ${parametersToType(query)};
export type ${route.typePrefix}Body = ${schemaToType(body)};
export type ${route.typePrefix}Response = ${schemaToType(response)};
export interface ${inputType} {
\treadonly params?: ${route.typePrefix}Params;
\treadonly query?: ${route.typePrefix}Query;
\treadonly body?: ${route.typePrefix}Body;
\treadonly headers?: HeadersInit;
\treadonly signal?: AbortSignal;
}
`;
}

function renderInstanceFields(
	namespaces: Map<string, readonly RouteModel[]>,
): string {
	const fields = Array.from(namespaces.entries()).map(([namespace, routes]) =>
		`\treadonly ${namespace}: ${renderNamespaceType(routes)};`
	);
	return ['\toptions: CodexaSdkOptions;', ...fields].join('\n');
}

function renderRuntimeInstanceFields(
	namespaces: Map<string, readonly RouteModel[]>,
): string {
	const fields = Array.from(namespaces.keys()).map((namespace) =>
		`\t${namespace};`
	);
	return ['\toptions;', ...fields].join('\n');
}

function renderNamespaceType(routes: readonly RouteModel[]): string {
	return `{
${routes.map(renderDeclarationMethod).join('\n')}
\t}`;
}

function renderInstanceNamespaceAssignments(
	namespaces: Map<string, readonly RouteModel[]>,
): string {
	return Array.from(namespaces.entries()).map(([namespace, routes]) =>
		`\t\tthis.${namespace} = {
${routes.map(renderInstanceMethod).join('\n')}
\t\t};`
	).join('\n');
}

function renderRuntimeInstanceNamespaceAssignments(
	namespaces: Map<string, readonly RouteModel[]>,
): string {
	return Array.from(namespaces.entries()).map(([namespace, routes]) =>
		`\t\tthis.${namespace} = {
${routes.map(renderRuntimeInstanceMethod).join('\n')}
\t\t};`
	).join('\n');
}

function renderStaticNamespace(
	clientName: string,
	namespace: string,
	routes: readonly RouteModel[],
): string {
	return `\tstatic ${namespace} = {
${routes.map((route) => renderStaticMethod(clientName, route)).join('\n')}
\t};`;
}

function renderRuntimeStaticNamespace(
	clientName: string,
	namespace: string,
	routes: readonly RouteModel[],
): string {
	return `\tstatic ${namespace} = {
${
		routes.map((route) => renderRuntimeStaticMethod(clientName, route))
			.join('\n')
	}
\t};`;
}

function renderStaticMethod(clientName: string, route: RouteModel): string {
	return `\t\t${route.methodName}: Object.assign(
\t\t\t(input: ${route.typePrefix}Input = {}) => {
\t\t\t\t${clientName}.checkPermission(${JSON.stringify(route.permission)});
\t\t\t\treturn ${clientName}.request<${route.typePrefix}Response>(
\t\t\t\t\t${JSON.stringify(route.method)},
\t\t\t\t\t${JSON.stringify(route.path)},
\t\t\t\t\tmergeRouteInput(input, ${renderFixedHeaders(route.fixedHeaders)}),
\t\t\t\t);
\t\t\t},
\t\t\t{ __permission: ${JSON.stringify(route.permission)} },
\t\t) as CodexaSdkMethod<${route.typePrefix}Input, ${route.typePrefix}Response>,`;
}

function renderRuntimeStaticMethod(
	clientName: string,
	route: RouteModel,
): string {
	return `\t\t${route.methodName}: Object.assign(
\t\t\t(input = {}) => {
\t\t\t\t${clientName}.checkPermission(${JSON.stringify(route.permission)});
\t\t\t\treturn ${clientName}.request(
\t\t\t\t\t${JSON.stringify(route.method)},
\t\t\t\t\t${JSON.stringify(route.path)},
\t\t\t\t\tmergeRouteInput(input, ${renderFixedHeaders(route.fixedHeaders)}),
\t\t\t\t);
\t\t\t},
\t\t\t{ __permission: ${JSON.stringify(route.permission)} },
\t\t),`;
}

function renderInstanceMethod(route: RouteModel): string {
	return `\t\t\t${route.methodName}: Object.assign(
\t\t\t\t(input: ${route.typePrefix}Input = {}) => {
\t\t\t\t\tthis.checkPermission(${JSON.stringify(route.permission)});
\t\t\t\t\treturn this.request<${route.typePrefix}Response>(
\t\t\t\t\t\t${JSON.stringify(route.method)},
\t\t\t\t\t\t${JSON.stringify(route.path)},
\t\t\t\t\t\tmergeRouteInput(input, ${renderFixedHeaders(route.fixedHeaders)}),
\t\t\t\t\t);
\t\t\t\t},
\t\t\t\t{ __permission: ${JSON.stringify(route.permission)} },
\t\t\t) as CodexaSdkMethod<${route.typePrefix}Input, ${route.typePrefix}Response>,`;
}

function renderRuntimeInstanceMethod(route: RouteModel): string {
	return `\t\t\t${route.methodName}: Object.assign(
\t\t\t\t(input = {}) => {
\t\t\t\t\tthis.checkPermission(${JSON.stringify(route.permission)});
\t\t\t\t\treturn this.request(
\t\t\t\t\t\t${JSON.stringify(route.method)},
\t\t\t\t\t\t${JSON.stringify(route.path)},
\t\t\t\t\t\tmergeRouteInput(input, ${renderFixedHeaders(route.fixedHeaders)}),
\t\t\t\t\t);
\t\t\t\t},
\t\t\t\t{ __permission: ${JSON.stringify(route.permission)} },
\t\t\t),`;
}

function renderFixedHeaders(headers: readonly FixedHeader[]): string {
	if (headers.length === 0) return '[]';
	return `[${
		headers.map((header) =>
			`[${JSON.stringify(header.name)}, ${JSON.stringify(header.value)}]`
		).join(', ')
	}]`;
}

function renderDeclarationNamespace(
	namespace: string,
	routes: readonly RouteModel[],
	options: { readonly static: boolean },
): string {
	return `\t${options.static ? 'static ' : ''}${namespace}: ${
		renderNamespaceType(routes)
	};`;
}

function renderDeclarationMethod(route: RouteModel): string {
	return `\t\treadonly ${route.methodName}: CodexaSdkMethod<${route.typePrefix}Input, ${route.typePrefix}Response>;`;
}

function firstRequestBodySchema(
	operation: OpenApiOperation,
): JsonSchemaObject | undefined {
	const content = operation.requestBody?.content;
	if (content === undefined) return undefined;
	return content['application/json']?.schema ??
		Object.values(content).at(0)?.schema;
}

function firstSuccessResponseSchema(
	operation: OpenApiOperation,
): JsonSchemaObject | undefined {
	const responses = Object.entries(operation.responses).sort((
		[left],
		[right],
	) => left.localeCompare(right));
	const success = responses.find(([status]) => status.startsWith('2')) ??
		responses[0];
	if (success === undefined || success[1].content === undefined) {
		return undefined;
	}
	return success[1].content['application/json']?.schema ??
		Object.values(success[1].content).at(0)?.schema;
}

function parametersToType(parameters: readonly OpenApiParameter[]): string {
	if (parameters.length === 0) return 'Record<string, never>';
	const fields = parameters.map((parameter) =>
		`\treadonly ${JSON.stringify(parameter.name)}${
			parameter.required ? '' : '?'
		}: ${schemaToType(parameter.schema)};`
	);
	return `{\n${fields.join('\n')}\n}`;
}

function schemaToType(schema: JsonSchemaObject | undefined): string {
	if (schema === undefined) return 'unknown';
	const rendered = renderSchemaType(schema);
	const nullable = schema.nullable === true ||
		(Array.isArray(schema.type) && schema.type.includes('null'));
	return nullable && rendered !== 'null' ? `${rendered} | null` : rendered;
}

function renderSchemaType(schema: JsonSchemaObject): string {
	if (schema.const !== undefined) return JSON.stringify(schema.const);
	if (Array.isArray(schema.enum)) {
		return schema.enum.map((value) => JSON.stringify(value)).join(' | ') ||
			'unknown';
	}
	if (Array.isArray(schema.anyOf)) {
		return schema.anyOf.map((item) => schemaToType(item)).join(' | ');
	}
	if (Array.isArray(schema.oneOf)) {
		return schema.oneOf.map((item) => schemaToType(item)).join(' | ');
	}
	if (Array.isArray(schema.allOf)) {
		return schema.allOf.map((item) => schemaToType(item)).join(' & ');
	}

	const schemaTypes = Array.isArray(schema.type)
		? schema.type.filter((type) => type !== 'null')
		: schema.type === undefined
		? []
		: [schema.type];
	if (schemaTypes.length > 1) {
		return schemaTypes.map((type) =>
			renderSchemaType({ ...schema, type, nullable: false })
		).join(' | ');
	}

	const schemaType = schemaTypes[0];
	if (schemaType === 'null') return 'null';
	if (schemaType === 'string') return 'string';
	if (schemaType === 'number' || schemaType === 'integer') return 'number';
	if (schemaType === 'boolean') return 'boolean';
	if (schemaType === 'array') {
		return `readonly (${schemaToType(schema.items)})[]`;
	}
	if (schemaType === 'object' || schema.properties !== undefined) {
		return objectSchemaToType(schema);
	}
	return 'unknown';
}

function objectSchemaToType(schema: JsonSchemaObject): string {
	const properties = schema.properties ?? {};
	const required = new Set(schema.required ?? []);
	const fields = Object.entries(properties).map(([key, value]) =>
		`\treadonly ${JSON.stringify(key)}${required.has(key) ? '' : '?'}: ${
			schemaToType(value)
		};`
	);
	if (isRecord(schema.additionalProperties)) {
		fields.push(
			fields.length === 0
				? `\treadonly [key: string]: ${
					schemaToType(schema.additionalProperties)
				};`
				: '\treadonly [key: string]: unknown;',
		);
	} else if (schema.additionalProperties === true) {
		fields.push('\treadonly [key: string]: unknown;');
	}
	return fields.length === 0
		? 'Record<string, unknown>'
		: `{\n${fields.join('\n')}\n}`;
}
